# Generated by Django 3.1.1 on 2020-10-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201018_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
