# Generated by Django 3.1.1 on 2020-10-09 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201008_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 8, 46, 50, 350401)),
        ),
    ]
