# Generated by Django 3.1.1 on 2020-10-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20201009_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(blank=True, choices=[('Fashion', 'Fashion'), ('Gadgets', 'Gadgets'), ('Clothes', 'Clothes'), ('Shoes', 'Shoes'), ('Food', 'Food'), ('Medications', 'Medications'), ('Art', 'Art'), ('Skincare', 'Skincare'), ('Makeup', 'Makeup')], default='Fashion', max_length=255),
        ),
    ]
